apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docmost
  
resources:
  - database.yaml
  - pooler.yaml
  - deployment-docmost.yaml
  - deployment-redis.yaml
  - http-route.yaml
  - namespace.yaml
  - services.yaml
  - storages.yaml