apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: docmost-pooler
  namespace: docmost
spec:
  cluster:
    name: docmost-db
  instances: 3                  # Highly Available pooler
  type: rw                      # Points to the Primary (Read/Write)
  
  pgbouncer:
    poolMode: session           # Recommended for HedgeDoc/General apps
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
