apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost
  namespace: docmost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost
  template:
    metadata:
      labels:
        app: docmost
    spec:
      initContainers:
        # Optional: Wait for DB to be ready
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z docmost-db-rw 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: docmost
          image: docmost/docmost:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: storage
              mountPath: /app/data/storage
          env:
            - name: APP_URL
              value: "http://docmost.home"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: docmost-secret
                  key: APP_SECRET
            - name: REDIS_URL
              value: "redis://redis:6379"
            
            # Extract CNPG credentials to build connection string
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: docmost-db-app 
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: docmost-db-app
                  key: password
            - name: DB_HOST
              value: docmost-pooler
              #valueFrom:
              #  secretKeyRef:
              #    name: docmost-db-app
              #    key: host
            # CNPG Service usually ends in -rw for ReadWrite connections
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: docmost-db-app
                  key: dbname
          # Override command to construct DATABASE_URL dynamically
          command: ["/bin/sh", "-c"]
          args:
            - |
              export DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
              # Execute the original entrypoint
              exec docker-entrypoint.sh npm run start
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: docmost-storage