apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: docmost
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-storage
  namespace: docmost
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi