apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

resources:
  - namespace.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

helmCharts:
  - name: cloudnative-pg
    releaseName: cnpg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.27.0
    includeCRDs: true