apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-init-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    # Minimal config to expose ports correctly
    http:
      address: 0.0.0.0:80
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53