apiVersion: batch/v1
kind: CronJob
metadata:
  name: adguard-sync
  namespace: adguard-sync
spec:
  schedule: "*/1 * * * *" # Runs every minute
  successfulJobsHistoryLimit: 3 # Keep last 3 successful jobs
  failedJobsHistoryLimit: 3 # Keep last 3 failed jobs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: adguard-sync
              image: ghcr.io/bakito/adguardhome-sync
              command: ["/opt/go/adguardhome-sync", "run", "--config", "/config.yaml"]
              env:
                - name: ORIGIN_URL
                  value: "http://adguard-primary.adguard.svc.cluster.local"
                - name: ORIGIN_INSECURE_SKIP_VERIFY
                  value: "true"
                - name: ORIGIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: adguard-credentials
                      key: username
                - name: ORIGIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: adguard-credentials
                      key: password
                - name: REPLICA1_URL
                  value: "http://adguard-replica.adguard.svc.cluster.local"
                - name: REPLICA1_INSECURE_SKIP_VERIFY
                  value: "true"
                - name: REPLICA1_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: adguard-credentials
                      key: username
                - name: REPLICA1_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: adguard-credentials
                      key: password
                - name: FEATURES_DNS_REWRITES
                  value: "true"
                - name: FEATURES_DNS_SERVER_CONFIG
                  value: "true"
                - name: PRINT_CONFIG_ONLY
                  value: "false"
                - name: LOG_LEVEL
                  value: info
                - name: API_PORT
                  value: "0"
          restartPolicy: OnFailure