apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config-map.yaml
  - deployment-primary.yaml
  - deployment-replica.yaml
  - storage.yaml
  - services.yaml
  - load-balancer.yaml
  - http-route.yaml
  # - cron-job.yaml
