apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-primary-data
  namespace: adguard
spec:
  storageClassName: longhorn
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-replica-data
  namespace: adguard
spec:
  storageClassName: longhorn
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi