apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hedgedoc-db
  namespace: hedgedoc
spec:
  instances: 3
  
  storage:
    size: 5Gi
    storageClass: longhorn

  backup:
    barmanObjectStore:
      destinationPath: s3://hedgedoc-backup/
      endpointURL: https://hel1.your-objectstorage.com
      s3Credentials:                                          # secret.yaml is saved in Proton Pass!
        accessKeyId:
          name: s3-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-backup-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "12m"                                    # Retention policy: Keep backups for 12 months

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          "cnpg.io/cluster": hedgedoc-db

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: app
      owner: app
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
  namespace: hedgedoc
spec:
  schedule: "0 0 2 * * *"                             # Every day at 2:00 AM
  cluster:
    name: hedgedoc-db