apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedgedoc
  namespace: hedgedoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc
  template:
    metadata:
      labels:
        app: hedgedoc
    spec:
      containers:
      - name: hedgedoc
        image: quay.io/hedgedoc/hedgedoc:1.10.5
        ports:
        - containerPort: 3000
        env:
        - name: CMD_DB_DIALECT
          value: "postgres"
        - name: CMD_DB_HOST
          value: "hedgedoc-pooler"        # Pooler
        - name: CMD_DB_PORT
          value: "5432"
        - name: CMD_DB_DATABASE
          value: "app"                    # Default CNPG database name
        - name: CMD_DB_USER
          valueFrom:
            secretKeyRef:
              name: hedgedoc-db-app       # Secret created by CNPG
              key: username
        - name: CMD_DB_PASS
          valueFrom:
            secretKeyRef:
              name: hedgedoc-db-app       # Secret created by CNPG
              key: password
        - name: CMD_DOMAIN
          value: "hedgedoc.home"   
        - name: CMD_PROTOCOL_USESSL
          value: "false"
        - name: CMD_URL_ADDPORT
          value: "false"