apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hedgedoc
  
resources:
  - database.yaml
  - pooler.yaml
  - deployment.yaml
  - http-route.yaml
  - namespace.yaml
  - service.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

secretGenerator:
  - name: hedgedoc-conf
    literals:
      - CMD_SESSION_SECRET=ArE7nz0qwE2XXv7MWW08A7KnQhHYv2wXw