apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: jellyfin
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jellyfin
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        topology.kubernetes.io/zone: Dagobah
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.1.0-nightly
          ports:
            - name: http
              containerPort: 7878
          envFrom:
            - configMapRef:
                name: common-env
                optional: true
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
              subPath: data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: data
          persistentVolumeClaim:
            claimName: jellyfin-media