apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: affine-route
  namespace: affine
spec:
  hostnames:
    - affine.home
  parentRefs:
    - kind: Gateway
      name: public-gateway
      namespace: kube-system
  rules:
    - backendRefs:
        - name: affine
          port: 3010
      matches:
        - path:
            type: PathPrefix
            value: /