apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database.yaml
  - deployment-affine.yaml
  - deployment-redis.ya
  - image-catalog.yaml
  - http-route.yaml
  - service-affine.yaml
  - service-redis.yaml
  - storage-redis.yaml
  - storage-affine.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true