apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: affine

resources:
  - namespace.yaml
  - storage.yaml
  - redis.yaml
  - database.yaml
  - deployment.yaml
  - http-route.yaml