apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-redis-pvc
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Gi