apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-storage-pvc
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 10Gi
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-config-pvc
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Gi